name: Android CI-CD for StreamPlayer App

on:
  push:
    branches:
      - master
      - feature/esteira-ci-cd

  workflow_dispatch:
    inputs:
      app_id:
        description: 'The application Id of the current build'
        required: true
      branch:
        description: 'The branch from which we have to build'
        required: true

jobs:
  prepare_environment:
    name: Prepare environment and setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Clean
        run: ./gradlew clean

  run_lint:
    name: Run Kotlin Lint analyser
    needs: prepare_environment

    steps:
      - name: Gradle Lint
        run: ./gradlew lint

  run_unit_test:
    name: Run unit tests
    needs: prepare_environment

    steps:
      - name: Gradle Unit tests
        run: ./gradlew testDebugUnitTest

  run_build:
    name: Generate AAR and APK files
    needs: prepare_environment

    steps:
      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Gradle Build and generating apk files
        if: always()
        run: ./gradlew build

  deploy_apk:
    name: Upload AAR files
    needs: run_build

    steps:
      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            dog_network/build/outputs/aar

     
