name: Android CI-CD for StreamPlayer App

on:
  push:
    branches:
      - master
      - feature/esteira-ci-cd

jobs:
  prepare_environment:
    name: Prepare environment and setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Clean
        run: ./gradlew clean

  run_lint:
    name: Run Kotlin Lint analyser
    runs-on: ubuntu-latest
    needs: prepare_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run lint
        run: ./gradlew lint

  run_unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: prepare_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew test

  run_build:
    name: Generate AAR and APK files
    runs-on: ubuntu-latest
    needs: prepare_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Gradle Build and generating apk files
        if: always()
        run: ./gradlew build

  deploy_apk:
    name: Upload AAR files
    runs-on: ubuntu-latest
    needs: run_build

    steps:
      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            dog_network/build/outputs/aar

     
