name: Android CI-CD for StreamPlayer App

on:
  pull_request:
    branches:
      - master
      - '*'

jobs:
#  test:
#    name: Run Unit Tests
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name : Check out Git Repository
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Clean
        run: ./gradlew clean

      - name: Gradle Lint
        run: ./gradlew lint