name: Android CI-CD for StreamPlayer App

on:
  push:
    branches:
      - master
      - feature/esteira-ci-cd

  workflow_dispatch:
    inputs:
      app_id:
        description: 'The application Id of the current build'
        required: true
      branch:
        description: 'The branch from which we have to build'
        required: true

jobs:
  basic_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions.
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            dog_network/build/outputs/aar

#
#jobs:
##  test:
##    name: Run Unit Tests
##    runs-on: ubuntu-latest
##    permissions:
##      contents: read
##      packages: write
#
#  build:
#    name: Build android app
#    runs-on: ubuntu-latest
#
#    steps:
#      - name : Check out Git Repository
#        uses: actions/checkout@v2
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Gradle Clean
#        run: ./gradlew clean
#
#      - name: Gradle Lint
#        run: ./gradlew lint